server:
  port: 8767
  
eureka:
  instance:
    hostname: peer3
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceurl:
      defaultZone: http://peer1:8761/eureka/

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/oenday87/cms-config
          #searchPaths: WebContent
          label: master
#指定git的uri,uri是git仓库地址和项目中的路径,searchPaths是指仓库地址的指定目录下
